version: '3'

services:
  db:
    image: mysql:5.7.29
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: Africa/Tunis
    volumes:
      - ./127.0.0.1/mysql:/var/lib/mysql

  moodle:
    build: ./
    depends_on:
      - db
    restart: unless-stopped
    links:
      - db:db
    volumes:
      - ./127.0.0.1/mysql:/web_data/db_data
      - ./127.0.0.1/web:/web_data/public_html
      - ./127.0.0.1/moodledata:/web_data/moodledata
    hostname: 127.0.0.1
    environment:
      FILEMANAGER_ROOT_PATH: '/web_data'
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: password
      ADMIN_EMAIL: admin@localhost.tn
      VIRTUAL_HOST: 127.0.0.1
      TZ: Africa/Tunis
    ports:
      - 80:80
