version: '2'
services:
  reverse-proxy:
  db:
    image: mysql:$MYSQL_V
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: $DATABASE_NAME
      MYSQL_USER: $DATABASE_USER
      MYSQL_PASSWORD: $DATABASE_PASSWORD
      MYSQL_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
      TZ: $TIMEZONE
    volumes:
      - ./$DOMAIN_NAME/volumes/db_data:/var/lib/mysql
  moodle:
    image: mindhosting/moodle:latest
    depends_on:
      - db
      - reverse-proxy
    restart: unless-stopped
    links:
      - $DATABASE_HOST:$DATABASE_HOST
    volumes:
      - ./$DOMAIN_NAME/volumes/public_html:/web_data/public_html
      - ./$DOMAIN_NAME/volumes/moodledata:/web_data/moodledata
      # FOR DUPLICATI BACKUP PURPUSE
      - ./$DOMAIN_NAME/volumes/db_data:/web_data/db_data
      - ./$DOMAIN_NAME/volumes/backup:/web_data/backup
      VIRTUAL_HOST: $DOMAIN_NAME
      LETSENCRYPT_HOST: $DOMAIN_NAME
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL

    hostname: $DOMAIN_NAME
    environment:
      FILE_MANAGER_USER: $FILE_MANAGER_USER
      FILE_MANAGER_PASSWORD: $FILE_MANAGER_PASSWORD
      MOODLE_DB_TYPE: mysqli
      MOODLE_DB_HOST: $DATABASE_HOST
      MOODLE_DB_USER: $DATABASE_USER
      MOODLE_DB_NAME: $DATABASE_NAME
      MOODLE_DB_PASS: $DATABASE_PASSWORD
      MOODLE_DB_PRFX: mdl_
      MOODLE_DATA_ROOT: /web_data/moodledata
      MOODLE_DIRECTORY_PERMISSIONS: 02777
      MOODLE_ADMIN_DIRECTORY: admin
      MOODLE_HOST_PROTOCOLE: https
      VIRTUAL_HOST: '$DOMAIN_NAME'
      TZ: $TIMEZONE
      LANG: $LANG
      ADMINUSER: $ADMINUSER
      ADMINPASS: $ADMINPASS
      ADMINEMAIL: $ADMINEMAIL
      FULLNAME: $FULLNAME
      SHORTNAME: $SHORTNAME
      VIRTUAL_HOST: duplicat.$DOMAIN_NAME
      LETSENCRYPT_HOST: duplicati.$DOMAIN_NAME
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL

  duplicati:
    image: linuxserver/duplicati
    restart: unless-stopped
    depends_on:
      - reverse-proxy
    environment:
      PUID: 1000
      PGID: 1000
      TZ: $TIMEZONE
      CLI_ARGS: #optional
    volumes:
      # TO CONTROLE DOCKER SOCK AND DOCKER TO STOP/START MYSQL CONTAINER BEFORE/AFTER BACKUP
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./$DOMAIN_NAME/volumes/backup/script.sh:/usr/bin/script.sh
      # ACCESS TO VOLUME SOURCES
      - ./$DOMAIN_NAME/volumes:/source
      # BACKUP DISTINATION
      - ./$DOMAIN_NAME/volumes/backup/backups:/backups
      # DUPLICATI CONFIGURATION
      - ./$DOMAIN_NAME/volumes/backup/config:/config
    hostname: $DOMAIN_NAME
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
      - reverse-proxy
    links:
      - $DATABASE_HOST:$DATABASE_HOST
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
      PMA_HOST: $DATABASE_HOST
      #PMA_ABSOLUTE_URI: $WEB_PROTOCOLE://phpmyadmin.$DOMAIN_NAME/
      TZ: $TIMEZONE
      VIRTUAL_HOST: duplicat.$DOMAIN_NAME
      LETSENCRYPT_HOST: duplicati.$DOMAIN_NAME
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
